name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  unified:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - name: Install deps
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn run lint
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: "Unit Tests"
        run: 'yarn run test:unit'
      - name: "Integrations Tests"
        run: 'yarn run test:integrations'
      - name: Set branch name for Cloudflare Pages
        id: cf-branch
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "CF_BRANCH_NAME=preview" >> $GITHUB_ENV
          else
            echo "CF_BRANCH_NAME=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
          fi

      # Deploy Docs
      - name: Create GitHub Deployment for Docs
        id: docs-deployment
        uses: octokit/request-action@v2
        with:
          route: POST /repos/${{ github.repository }}/deployments
          environment: gopher-docs-preview
          ref: ${{ github.ref }}
          description: Deploying Docs preview
          auto_merge: false
          payload: '{"project": "docs"}'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docs to Cloudflare Pages
        id: docs-publish
        uses: cloudflare/wrangler-action@v3
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2238a825c5aca59233eab1f221f7aefb
          command: pages deploy ./docs/build --project-name=sprinter-docs --branch=${{ env.CF_BRANCH_NAME }}

      - name: Update Docs Deployment Status
        uses: octokit/request-action@v2
        with:
          route: POST /repos/${{ github.repository }}/deployments/${{ steps.docs-deployment.outputs.deployment_id }}/statuses
          state: success
          environment_url: ${{ steps.docs-publish.outputs.deployment-url }}
          description: Docs deployed successfully
          token: ${{ secrets.GITHUB_TOKEN }}

      # Deploy POC
      - name: Create GitHub Deployment for POC
        id: poc-deployment
        uses: octokit/request-action@v2
        with:
          route: POST /repos/${{ github.repository }}/deployments
          environment: gopher-poc-preview
          ref: ${{ github.ref }}
          description: Deploying POC preview
          auto_merge: false
          payload: '{"project": "poc"}'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish POC to Cloudflare Pages
        id: poc-publish
        uses: cloudflare/wrangler-action@v3
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2238a825c5aca59233eab1f221f7aefb
          command: pages deploy ./web/.svelte-kit/cloudflare --project-name=sprinter-poc --branch=${{ env.CF_BRANCH_NAME }}

      - name: Update POC Deployment Status
        uses: octokit/request-action@v2
        with:
          route: POST /repos/${{ github.repository }}/deployments/${{ steps.poc-deployment.outputs.deployment_id }}/statuses
          state: success
          environment_url: ${{ steps.poc-publish.outputs.deployment-url }}
          description: POC deployed successfully
          token: ${{ secrets.GITHUB_TOKEN }}
