name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  unified:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - name: Install deps
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn run lint
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: "Unit Tests"
        run: 'yarn run test:unit'
      - name: "Integrations Tests"
        run: 'yarn run test:integrations'
      - name: Set branch name for Cloudflare Pages
        id: cf-branch
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "CF_BRANCH_NAME=preview" >> $GITHUB_ENV
          else
            echo "CF_BRANCH_NAME=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
          fi
      - name: Publish Docs to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2238a825c5aca59233eab1f221f7aefb
          environment: sprinter-docs
          command: pages deploy ./docs/build --project-name=sprinter-docs --branch=${{ env.CF_BRANCH_NAME }}
      - name: Publish POC to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2238a825c5aca59233eab1f221f7aefb
          environment: sprinter-poc
          command: pages deploy ./web/.svelte-kit/cloudflare --project-name=sprinter-poc --branch=${{ env.CF_BRANCH_NAME }}
